// AUTO-GENERATED by scripts/build-local-catalog.mjs — do not edit by hand.
// Regenerate with: node scripts/build-local-catalog.mjs
import type { CourseWithLessons } from "@lifeskl/core";

export const LOCAL_COURSES: CourseWithLessons[] = [
  {
    "id": "personal-finance",
    "slug": "personal-finance",
    "title": "Personal Finance",
    "description": "Budgets, saving, credit, investing, scams & taxes — money skills for real life.",
    "emoji": "💵",
    "sortOrder": 0,
    "lessons": [
      {
        "id": "personal-finance__what-is-a-budget",
        "slug": "what-is-a-budget",
        "title": "What is a budget (and why you need one)",
        "description": "Give every dollar a job before the month starts.",
        "xpReward": 20,
        "sortOrder": 1,
        "unit": 1
      },
      {
        "id": "personal-finance__financial-goals",
        "slug": "financial-goals",
        "title": "Financial goals: from \"someday\" to a deadline",
        "description": "Turn 'I want money' into a plan with a number and a date.",
        "xpReward": 20,
        "sortOrder": 2,
        "unit": 1
      },
      {
        "id": "personal-finance__saving-regularly",
        "slug": "saving-regularly",
        "title": "Saving regularly: pay yourself first",
        "description": "Make saving automatic — small, weekly, unstoppable.",
        "xpReward": 20,
        "sortOrder": 3,
        "unit": 2
      },
      {
        "id": "personal-finance__savings-accounts-interest",
        "slug": "savings-accounts-interest",
        "title": "Savings accounts & interest: park it right",
        "description": "Put your money where it's safe, insured, and quietly growing.",
        "xpReward": 20,
        "sortOrder": 4,
        "unit": 2
      },
      {
        "id": "personal-finance__borrowing-credit",
        "slug": "borrowing-credit",
        "title": "Borrowing & credit: the real price of 'buy now'",
        "description": "Borrow like you've read the fine print — because you have.",
        "xpReward": 25,
        "sortOrder": 5,
        "unit": 3
      },
      {
        "id": "personal-finance__credit-scores",
        "slug": "credit-scores",
        "title": "Credit scores: the number that follows you",
        "description": "Three digits that decide what borrowing costs you.",
        "xpReward": 25,
        "sortOrder": 6,
        "unit": 3
      },
      {
        "id": "personal-finance__basics-of-investing",
        "slug": "basics-of-investing",
        "title": "The basics of investing",
        "description": "Plant money today, pick fruit for decades — starting with $5.",
        "xpReward": 25,
        "sortOrder": 7,
        "unit": 4
      },
      {
        "id": "personal-finance__risk-and-reward",
        "slug": "risk-and-reward",
        "title": "Risk and reward: the balancing act",
        "description": "Match every dollar to its deadline — and keep your cool when markets wobble.",
        "xpReward": 25,
        "sortOrder": 8,
        "unit": 4
      },
      {
        "id": "personal-finance__needs-vs-wants",
        "slug": "needs-vs-wants",
        "title": "Needs vs wants (and the ads that blur them)",
        "description": "Tell needs from wants before the ads decide for you.",
        "xpReward": 20,
        "sortOrder": 9,
        "unit": 5
      },
      {
        "id": "personal-finance__protecting-your-money",
        "slug": "protecting-your-money",
        "title": "Protecting your money",
        "description": "Build the safety net before life takes a swing.",
        "xpReward": 25,
        "sortOrder": 10,
        "unit": 6
      },
      {
        "id": "personal-finance__debt-and-scams",
        "slug": "debt-and-scams",
        "title": "Debt traps and scams",
        "description": "Spot the traps that eat paychecks — minimum payments, payday loans, and scammers in costume.",
        "xpReward": 25,
        "sortOrder": 11,
        "unit": 6
      },
      {
        "id": "personal-finance__financial-roadmap",
        "slug": "financial-roadmap",
        "title": "Your financial roadmap",
        "description": "Point your money at the life you actually want.",
        "xpReward": 30,
        "sortOrder": 12,
        "unit": 7
      },
      {
        "id": "personal-finance__taxes-and-planning",
        "slug": "taxes-and-planning",
        "title": "Taxes and long-term planning",
        "description": "See where your paycheck really goes — and make the after-tax part work harder.",
        "xpReward": 30,
        "sortOrder": 13,
        "unit": 7
      }
    ]
  },
  {
    "id": "money",
    "slug": "money",
    "title": "Money & Finance",
    "description": "Taxes, budgeting, credit, saving & paychecks.",
    "emoji": "💰",
    "sortOrder": 1,
    "lessons": [
      {
        "id": "money__reading-a-payslip",
        "slug": "reading-a-payslip",
        "title": "Reading a payslip",
        "description": "Gross, net, and where the rest went.",
        "xpReward": 10,
        "sortOrder": 1,
        "unit": 1
      },
      {
        "id": "money__minimum-payment-trap",
        "slug": "minimum-payment-trap",
        "title": "The minimum payment trap",
        "description": "Why \"just pay the minimum\" quietly grows your debt.",
        "xpReward": 10,
        "sortOrder": 2,
        "unit": 1
      },
      {
        "id": "money__budget-that-sticks",
        "slug": "budget-that-sticks",
        "title": "A budget that sticks",
        "description": "The 50/30/20 rule, minus the spreadsheet dread.",
        "xpReward": 15,
        "sortOrder": 3,
        "unit": 1
      }
    ]
  },
  {
    "id": "how-to-learn",
    "slug": "how-to-learn",
    "title": "How to Learn",
    "description": "Study smarter, not harder — mindset, time, focus, memory & test skills backed by science.",
    "emoji": "🧠",
    "sortOrder": 1,
    "lessons": [
      {
        "id": "how-to-learn__how-learning-works",
        "slug": "how-learning-works",
        "title": "How learning actually works",
        "description": "Your brain isn't fixed — learning is a skill you can build.",
        "xpReward": 20,
        "sortOrder": 1,
        "unit": 1
      },
      {
        "id": "how-to-learn__growth-mindset",
        "slug": "growth-mindset",
        "title": "Growth vs. fixed mindset",
        "description": "The story you tell yourself after a setback changes the outcome.",
        "xpReward": 20,
        "sortOrder": 2,
        "unit": 1
      },
      {
        "id": "how-to-learn__the-priority-matrix",
        "slug": "the-priority-matrix",
        "title": "Urgent vs. important",
        "description": "The Eisenhower matrix: stop letting urgent crowd out important.",
        "xpReward": 20,
        "sortOrder": 3,
        "unit": 2
      },
      {
        "id": "how-to-learn__beat-procrastination",
        "slug": "beat-procrastination",
        "title": "Beating procrastination",
        "description": "Procrastination is about feelings, not laziness — here's the way out.",
        "xpReward": 20,
        "sortOrder": 4,
        "unit": 2
      },
      {
        "id": "how-to-learn__plan-your-time",
        "slug": "plan-your-time",
        "title": "Plan a week that holds",
        "description": "Build a realistic schedule and work with your own rhythm.",
        "xpReward": 20,
        "sortOrder": 5,
        "unit": 2
      },
      {
        "id": "how-to-learn__critical-thinking",
        "slug": "critical-thinking",
        "title": "Think it through",
        "description": "Question claims, weigh evidence, and don't get fooled.",
        "xpReward": 20,
        "sortOrder": 6,
        "unit": 3
      },
      {
        "id": "how-to-learn__metacognition",
        "slug": "metacognition",
        "title": "Thinking about your thinking",
        "description": "Plan, monitor, and check your own learning — the skill behind every skill.",
        "xpReward": 20,
        "sortOrder": 7,
        "unit": 3
      },
      {
        "id": "how-to-learn__blooms-taxonomy",
        "slug": "blooms-taxonomy",
        "title": "Levels of understanding",
        "description": "From memorizing facts to creating something new — Bloom's ladder.",
        "xpReward": 20,
        "sortOrder": 8,
        "unit": 3
      },
      {
        "id": "how-to-learn__active-listening",
        "slug": "active-listening",
        "title": "Listen like it counts",
        "description": "Real listening is active — in lectures and in life.",
        "xpReward": 20,
        "sortOrder": 9,
        "unit": 4
      },
      {
        "id": "how-to-learn__note-taking",
        "slug": "note-taking",
        "title": "Notes that actually work",
        "description": "Cornell, mind maps, and why your laptop might be hurting you.",
        "xpReward": 20,
        "sortOrder": 10,
        "unit": 4
      },
      {
        "id": "how-to-learn__active-reading",
        "slug": "active-reading",
        "title": "Read so it sticks",
        "description": "SQ3R: turn a textbook chapter into knowledge, not eye exercise.",
        "xpReward": 20,
        "sortOrder": 11,
        "unit": 4
      },
      {
        "id": "how-to-learn__test-anxiety",
        "slug": "test-anxiety",
        "title": "Calm under exam pressure",
        "description": "Nerves are normal — here's how to keep them from tanking your score.",
        "xpReward": 20,
        "sortOrder": 12,
        "unit": 5
      },
      {
        "id": "how-to-learn__study-and-test-taking",
        "slug": "study-and-test-taking",
        "title": "Study to learn, then ace the test",
        "description": "Practice like the test, then read questions like a detective.",
        "xpReward": 25,
        "sortOrder": 13,
        "unit": 5
      },
      {
        "id": "how-to-learn__how-memory-works",
        "slug": "how-memory-works",
        "title": "How memory actually works",
        "description": "Encode, store, retrieve — and how to make each one stick.",
        "xpReward": 25,
        "sortOrder": 14,
        "unit": 6
      },
      {
        "id": "how-to-learn__make-it-stick",
        "slug": "make-it-stick",
        "title": "Make it stick",
        "description": "The study habits science backs — and the popular ones that fail.",
        "xpReward": 25,
        "sortOrder": 15,
        "unit": 6
      },
      {
        "id": "how-to-learn__focus-and-mindfulness",
        "slug": "focus-and-mindfulness",
        "title": "Train your focus",
        "description": "Attention is trainable — beat distraction and find your flow.",
        "xpReward": 25,
        "sortOrder": 16,
        "unit": 7
      },
      {
        "id": "how-to-learn__a-healthy-brain",
        "slug": "a-healthy-brain",
        "title": "Fuel your brain",
        "description": "Sleep, move, eat, repeat — the body work that powers the mind.",
        "xpReward": 25,
        "sortOrder": 17,
        "unit": 7
      }
    ]
  },
  {
    "id": "health",
    "slug": "health",
    "title": "Health & Mind",
    "description": "Burnout, sleep, stress, habits & therapy basics.",
    "emoji": "🧠",
    "sortOrder": 2,
    "lessons": [
      {
        "id": "health__sleep-debt",
        "slug": "sleep-debt",
        "title": "Sleep is a budget too",
        "description": "Why the weekend lie-in never quite fixes the week.",
        "xpReward": 10,
        "sortOrder": 1,
        "unit": 1
      },
      {
        "id": "health__burnout-signals",
        "slug": "burnout-signals",
        "title": "Spotting burnout early",
        "description": "The warning lights before the engine seizes.",
        "xpReward": 10,
        "sortOrder": 2,
        "unit": 1
      }
    ]
  },
  {
    "id": "relationships",
    "slug": "relationships",
    "title": "Relationships",
    "description": "Boundaries, conflict, communication & dating.",
    "emoji": "💬",
    "sortOrder": 3,
    "lessons": [
      {
        "id": "relationships__boundaries-101",
        "slug": "boundaries-101",
        "title": "Saying no without the guilt",
        "description": "A boundary is about your behavior, not theirs.",
        "xpReward": 10,
        "sortOrder": 1,
        "unit": 1
      },
      {
        "id": "relationships__fair-fighting",
        "slug": "fair-fighting",
        "title": "Disagree without the damage",
        "description": "Complaints, criticism, and the kitchen sink.",
        "xpReward": 10,
        "sortOrder": 2,
        "unit": 1
      }
    ]
  },
  {
    "id": "digital",
    "slug": "digital",
    "title": "Digital Life",
    "description": "Privacy, scams, passwords & staying safe online.",
    "emoji": "🔐",
    "sortOrder": 4,
    "lessons": [
      {
        "id": "digital__password-hygiene",
        "slug": "password-hygiene",
        "title": "Passwords that actually protect",
        "description": "Length beats cleverness, and reuse is the killer.",
        "xpReward": 10,
        "sortOrder": 1,
        "unit": 1
      },
      {
        "id": "digital__spot-the-scam",
        "slug": "spot-the-scam",
        "title": "Spot the scam",
        "description": "Urgency, weird payment, secrecy — the scam triangle.",
        "xpReward": 10,
        "sortOrder": 2,
        "unit": 1
      }
    ]
  },
  {
    "id": "emotional-intelligence",
    "slug": "emotional-intelligence",
    "title": "Emotional Intelligence",
    "description": "Read your feelings, keep your cool, and handle people — the skills that actually run real life.",
    "emoji": "🫶",
    "sortOrder": 4,
    "lessons": [
      {
        "id": "emotional-intelligence__name-your-feelings",
        "slug": "name-your-feelings",
        "title": "Name what you feel",
        "description": "Put the right word on a feeling and it loosens its grip.",
        "xpReward": 20,
        "sortOrder": 1,
        "unit": 1
      },
      {
        "id": "emotional-intelligence__your-triggers",
        "slug": "your-triggers",
        "title": "Spot your triggers",
        "description": "The button that gets pushed — and how to see it coming.",
        "xpReward": 20,
        "sortOrder": 2,
        "unit": 1
      },
      {
        "id": "emotional-intelligence__values-and-blind-spots",
        "slug": "values-and-blind-spots",
        "title": "Your values & blind spots",
        "description": "What actually drives you — and what you can't see about yourself.",
        "xpReward": 20,
        "sortOrder": 3,
        "unit": 1
      },
      {
        "id": "emotional-intelligence__the-pause",
        "slug": "the-pause",
        "title": "The pause",
        "description": "The tiny gap between trigger and reaction is where your power lives.",
        "xpReward": 20,
        "sortOrder": 4,
        "unit": 2
      },
      {
        "id": "emotional-intelligence__cool-the-heat",
        "slug": "cool-the-heat",
        "title": "Cool the heat",
        "description": "Anger and anxiety are loud — here's how to turn the volume down.",
        "xpReward": 20,
        "sortOrder": 5,
        "unit": 2
      },
      {
        "id": "emotional-intelligence__venting-without-dumping",
        "slug": "venting-without-dumping",
        "title": "Vent without dumping",
        "description": "Let off steam in a way that helps — and doesn't torch the people around you.",
        "xpReward": 20,
        "sortOrder": 6,
        "unit": 2
      },
      {
        "id": "emotional-intelligence__reading-people",
        "slug": "reading-people",
        "title": "Read the room... and the person",
        "description": "Most of what people mean isn't in their words.",
        "xpReward": 20,
        "sortOrder": 7,
        "unit": 3
      },
      {
        "id": "emotional-intelligence__see-their-side",
        "slug": "see-their-side",
        "title": "See it their way",
        "description": "Understanding someone isn't the same as agreeing — and it's a superpower.",
        "xpReward": 20,
        "sortOrder": 8,
        "unit": 3
      },
      {
        "id": "emotional-intelligence__respecting-differences",
        "slug": "respecting-differences",
        "title": "Read the room & respect differences",
        "description": "The same move that kills in one room bombs in another.",
        "xpReward": 20,
        "sortOrder": 9,
        "unit": 3
      },
      {
        "id": "emotional-intelligence__feedback-both-ways",
        "slug": "feedback-both-ways",
        "title": "Feedback, both ways",
        "description": "How to give it without bruising — and take it without crumbling.",
        "xpReward": 20,
        "sortOrder": 10,
        "unit": 4
      },
      {
        "id": "emotional-intelligence__conflict-and-repair",
        "slug": "conflict-and-repair",
        "title": "From conflict to repair",
        "description": "Fighting fair, and fixing it after you mess up.",
        "xpReward": 20,
        "sortOrder": 11,
        "unit": 4
      },
      {
        "id": "emotional-intelligence__boundaries",
        "slug": "boundaries",
        "title": "Set a boundary that holds",
        "description": "A boundary is about what you'll do — not controlling them.",
        "xpReward": 20,
        "sortOrder": 12,
        "unit": 4
      },
      {
        "id": "emotional-intelligence__what-moves-you",
        "slug": "what-moves-you",
        "title": "What actually moves you",
        "description": "The difference between drive that lasts and drive that fizzles.",
        "xpReward": 25,
        "sortOrder": 13,
        "unit": 5
      },
      {
        "id": "emotional-intelligence__the-long-game",
        "slug": "the-long-game",
        "title": "The long game",
        "description": "Staying in it when the results just... aren't showing up yet.",
        "xpReward": 25,
        "sortOrder": 14,
        "unit": 5
      },
      {
        "id": "emotional-intelligence__emotional-discipline",
        "slug": "emotional-discipline",
        "title": "Emotional discipline",
        "description": "Doing the thing even when you don't feel like it.",
        "xpReward": 25,
        "sortOrder": 15,
        "unit": 5
      },
      {
        "id": "emotional-intelligence__say-it-without-exploding",
        "slug": "say-it-without-exploding",
        "title": "Say it without exploding",
        "description": "Honest AND kind — the assertive sweet spot.",
        "xpReward": 25,
        "sortOrder": 16,
        "unit": 6
      },
      {
        "id": "emotional-intelligence__hard-conversations",
        "slug": "hard-conversations",
        "title": "Hard conversations",
        "description": "How to have the talk you keep avoiding — without the drama.",
        "xpReward": 25,
        "sortOrder": 17,
        "unit": 6
      },
      {
        "id": "emotional-intelligence__digital-ei",
        "slug": "digital-ei",
        "title": "Tone in texts & DMs",
        "description": "Why \"ok.\" reads as cold — and how not to start fights online.",
        "xpReward": 25,
        "sortOrder": 18,
        "unit": 6
      },
      {
        "id": "emotional-intelligence__ei-at-work-and-school",
        "slug": "ei-at-work-and-school",
        "title": "EI at work & school",
        "description": "Often the thing that separates good from great — and you don't need a title.",
        "xpReward": 25,
        "sortOrder": 19,
        "unit": 7
      },
      {
        "id": "emotional-intelligence__difficult-people",
        "slug": "difficult-people",
        "title": "Difficult & draining people",
        "description": "You can't change them — but you can manage your side.",
        "xpReward": 25,
        "sortOrder": 20,
        "unit": 7
      },
      {
        "id": "emotional-intelligence__make-it-stick",
        "slug": "make-it-stick",
        "title": "Make EI stick",
        "description": "Turning all of this into who you actually are.",
        "xpReward": 25,
        "sortOrder": 21,
        "unit": 7
      }
    ]
  },
  {
    "id": "career",
    "slug": "career",
    "title": "Career & Work",
    "description": "Resumes, interviews, negotiation & email.",
    "emoji": "💼",
    "sortOrder": 5,
    "lessons": [
      {
        "id": "career__six-second-resume",
        "slug": "six-second-resume",
        "title": "The six-second resume",
        "description": "What recruiters actually see before deciding.",
        "xpReward": 10,
        "sortOrder": 1,
        "unit": 1
      },
      {
        "id": "career__salary-talk",
        "slug": "salary-talk",
        "title": "Talking salary without sweating",
        "description": "Anchors, ranges, and the power of a pause.",
        "xpReward": 10,
        "sortOrder": 2,
        "unit": 1
      }
    ]
  },
  {
    "id": "home",
    "slug": "home",
    "title": "Home & Repair",
    "description": "Leases, moving out, fixes & everyday maintenance.",
    "emoji": "🔧",
    "sortOrder": 6,
    "lessons": [
      {
        "id": "home__read-the-lease",
        "slug": "read-the-lease",
        "title": "Read the lease like a lawyer",
        "description": "The four clauses that decide your year.",
        "xpReward": 10,
        "sortOrder": 1,
        "unit": 1
      },
      {
        "id": "home__fix-or-call",
        "slug": "fix-or-call",
        "title": "Fix it or call it in?",
        "description": "What's yours, what's the landlord's, and the paper trail.",
        "xpReward": 10,
        "sortOrder": 2,
        "unit": 1
      }
    ]
  },
  {
    "id": "cooking",
    "slug": "cooking",
    "title": "Cooking & Food",
    "description": "Real meals, groceries, nutrition & not wasting it.",
    "emoji": "🍳",
    "sortOrder": 7,
    "lessons": [
      {
        "id": "cooking__pantry-foundations",
        "slug": "pantry-foundations",
        "title": "Stock a pantry like a pro",
        "description": "Ten staples, dozens of dinners.",
        "xpReward": 10,
        "sortOrder": 1,
        "unit": 1
      },
      {
        "id": "cooking__grocery-math",
        "slug": "grocery-math",
        "title": "Grocery math",
        "description": "Unit prices, store brands, and the hungry-shopper tax.",
        "xpReward": 10,
        "sortOrder": 2,
        "unit": 1
      }
    ]
  }
];
